// Centralized placeholder data for the admin dashboard.
//
// Every tab reads from here instead of hardcoding its own arrays, so
// wiring up a real database later means replacing the exports in this one
// file (with fetches from Postgres, most likely) rather than hunting
// through each component.

export const STAGES = ['New Leads', 'Quoting', 'Drafting', 'Client Review', 'Invoicing', 'Closed'];

export const PROJECTS = [
  {
    id: 1,
    stage: 'New Leads',
    title: 'Switchyard — Nagpur',
    client: 'GETCO',
    value: 420000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [],
    documents: { proposal: false, invoice: false },
  },
  {
    id: 2,
    stage: 'Quoting',
    title: '33kV Substation — Pune',
    client: 'Tata Power',
    value: 680000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [{ id: 1, item: 'Site survey — subcontractor', amount: 18000 }],
    documents: { proposal: false, invoice: false },
  },
  {
    id: 3,
    stage: 'Drafting',
    title: 'GIS Sub-station — Surat',
    client: 'Adani Power',
    value: 910000,
    blocked: true,
    discipline: 'Structural',
    ledger: [
      { id: 1, item: 'Soil testing', amount: 32000 },
      { id: 2, item: 'CAD contractor — 2 weeks', amount: 54000 },
    ],
    documents: { proposal: true, invoice: false },
  },
  {
    id: 4,
    stage: 'Client Review',
    title: 'Warehouse Fit-out — Bhiwandi',
    client: 'Amazon',
    value: 310000,
    blocked: false,
    discipline: 'Civil',
    ledger: [{ id: 1, item: 'Structural review — S K Saha', amount: 12000 }],
    documents: { proposal: true, invoice: false },
  },
  {
    id: 5,
    stage: 'Invoicing',
    title: 'Cement Plant — Satna',
    client: 'L&T',
    value: 550000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [{ id: 1, item: 'Site supervision', amount: 40000 }],
    documents: { proposal: true, invoice: true },
  },
  {
    id: 6,
    stage: 'Closed',
    title: 'Refinery Yard — Jamnagar',
    client: 'Reliance Industries',
    value: 1250000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [{ id: 1, item: 'Commissioning support', amount: 65000 }],
    documents: { proposal: true, invoice: true },
  },
  {
    id: 7,
    stage: 'New Leads',
    title: 'Rooftop Solar Tie-in — Nashik',
    client: 'MSEDCL',
    value: 190000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [],
    documents: { proposal: false, invoice: false },
  },
  {
    id: 8,
    stage: 'Quoting',
    title: 'Cold Storage Structural Review — Kolhapur',
    client: 'Mahindra Logistics',
    value: 260000,
    blocked: false,
    discipline: 'Structural',
    ledger: [],
    documents: { proposal: false, invoice: false },
  },
  {
    id: 9,
    stage: 'Drafting',
    title: 'Feeder Line Extension — Nagpur',
    client: 'MSEDCL',
    value: 410000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [{ id: 1, item: 'Route survey', amount: 21000 }],
    documents: { proposal: true, invoice: false },
  },
  {
    id: 10,
    stage: 'Closed',
    title: 'Textile Mill Retrofit — Surat',
    client: 'Welspun',
    value: 275000,
    blocked: false,
    discipline: 'Electrical',
    ledger: [{ id: 1, item: 'Commissioning support', amount: 15000 }],
    documents: { proposal: true, invoice: true },
  },
];

export const TENDERS = [
  {
    id: 1,
    source: 'MahaTenders',
    title: '110kV Grid Substation Upgrade — Aurangabad',
    location: 'Maharashtra, IN',
    estValue: 890000,
    deadline: '2026-10-02',
    status: 'new',
  },
  {
    id: 2,
    source: 'GeM',
    title: 'Structural Audit — Govt. Warehouse Complex',
    location: 'Nagpur, IN',
    estValue: 145000,
    deadline: '2026-09-25',
    status: 'new',
  },
  {
    id: 3,
    source: 'CPPP',
    title: 'Civil Works — District Hospital Annex',
    location: 'Nashik, IN',
    estValue: 620000,
    deadline: '2026-10-10',
    status: 'new',
  },
  {
    id: 4,
    source: 'MahaTenders',
    title: 'Electrical Retrofit — Textile Mill',
    location: 'Surat, IN',
    estValue: 275000,
    deadline: '2026-09-18',
    status: 'archived',
  },
  {
    id: 5,
    source: 'GeM',
    title: '33kV Feeder Line Extension',
    location: 'Nagpur, IN',
    estValue: 410000,
    deadline: '2026-09-30',
    status: 'converted',
  },
];

export const INVOICES = [
  {
    id: 1,
    project: 'Cement Plant — Satna',
    client: 'L&T',
    amount: 550000,
    status: 'sent',
    dueDate: '2026-09-20',
    remindersSent: 0,
  },
  {
    id: 2,
    project: 'Refinery Yard — Jamnagar',
    client: 'Reliance Industries',
    amount: 1250000,
    status: 'paid',
    dueDate: '2026-08-15',
    remindersSent: 0,
  },
  {
    id: 3,
    project: 'GIS Sub-station — Surat',
    client: 'Adani Power',
    amount: 320000,
    status: 'overdue',
    dueDate: '2026-09-05',
    remindersSent: 2,
  },
  {
    id: 4,
    project: 'Warehouse Fit-out — Bhiwandi',
    client: 'Amazon',
    amount: 310000,
    status: 'draft',
    dueDate: '2026-10-01',
    remindersSent: 0,
  },
];

export const TEAM = [
  {
    name: 'Suhas Patil',
    role: 'Founder & Principal',
    credential: 'B.Tech Electrical',
    discipline: 'All disciplines',
    draftsmen: 0,
  },
  {
    name: 'Mahesh Karia',
    role: 'Discipline Lead',
    credential: 'Electrical',
    discipline: 'Electrical',
    draftsmen: 3,
  },
  {
    name: 'Satyajeet Pimpalkar',
    role: 'Discipline Lead',
    credential: 'Civil',
    discipline: 'Civil',
    draftsmen: 2,
  },
  {
    name: 'S K Saha',
    role: 'Discipline Lead',
    credential: 'Structural',
    discipline: 'Structural',
    draftsmen: 2,
  },
];

export function formatINR(amount) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}